<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="fastlane.lanes">
    
    
    
      
      <testcase classname="fastlane.lanes" name="0: version_bump_podspec" time="0.011193">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="1: git_add" time="0.039033">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="2: git_commit" time="0.036264">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="3: git_tag_exists" time="0.019375">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="4: add_git_tag" time="0.047944">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="5: push_git_tags" time="8.424626">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="6: push_to_git_remote" time="5.635028">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="7: pod_lib_lint" time="213.343421">
        
          <failure message="/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/actions/actions_helper.rb:48:in `execute_action'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'&#10;Fastfile:44:in `block in parsing_binding'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane.rb:33:in `call'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/runner.rb:45:in `execute'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.108.0/bin/fastlane:23:in `&lt;top (required)&gt;'&#10;/usr/local/bin/fastlane:23:in `load'&#10;/usr/local/bin/fastlane:23:in `&lt;main&gt;'&#10;&#10;Exit status of command 'pod lib lint --allow-warnings' was 1 instead of 0.&#10;&#10; -&gt; MoyaMapper#&lt;Thread:0x00007f9acce10780@/usr/local/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/executable.rb:180 run&gt; terminated with exception (report_on_exception is true):&#10;/usr/local/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/executable.rb:184:in `readpartial': closed stream (IOError)&#10;	from /usr/local/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/executable.rb:184:in `block (2 levels) in reader'&#10;	from /usr/local/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/executable.rb:183:in `loop'&#10;	from /usr/local/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/executable.rb:183:in `block in reader'&#10;#&lt;Thread:0x00007f9acbce5500@/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/executable.rb:166 run&gt; terminated with exception (report_on_exception is true):&#10;/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/executable.rb:170:in `readpartial': stream closed in another thread (IOError)&#10;	from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/executable.rb:170:in `block (2 levels) in reader'&#10;	from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/executable.rb:169:in `loop'&#10;	from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/executable.rb:169:in `block in reader'&#10; -&gt; MoyaMapper (1.1.4)&#10;    - NOTE  | [MoyaMapper/MMCache, MoyaMapper/Rx, MoyaMapper/RxCache, and more...] xcodebuild:  note: Using new build system&#10;    - NOTE  | [MoyaMapper/MMCache, MoyaMapper/Rx, MoyaMapper/RxCache, and more...] xcodebuild:  note: Planning build&#10;    - NOTE  | [MoyaMapper/MMCache, MoyaMapper/Rx, MoyaMapper/RxCache, and more...] xcodebuild:  note: Constructing build description&#10;    - NOTE  | [MoyaMapper/MMCache, MoyaMapper/Rx, MoyaMapper/RxCache, and more...] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')&#10;    - ERROR | [iOS] [MoyaMapper/Core] unknown: Encountered an unknown error (416: unexpected token at '{&#10;        &quot;state&quot; : &quot;Shutdown&quot;,&#10;        &quot;availability&quot; : &quot;(available)&quot;,&#10;        &quot;name&quot; : &quot;iPhone 7&quot;,&#10;') during validation.&#10;&#10;[!] MoyaMapper did not pass validation, due to 1 error.&#10;You can use the `--no-clean` option to inspect any issue.&#10;" />
        
      </testcase>
    
  </testsuite>
</testsuites>
